"""
Where the bundled documentation lives, and what order it reads in.

Qt-free on purpose, like :mod:`PyXFocus.gui.wolter` and
:mod:`PyXFocus.gui.config`: ``tools/build_docs.py`` imports this to know what
to generate, and ``test_smoke.py`` imports it to check the generated HTML is
current. Neither should need PyQt5 installed, and
``test_qt_free_modules_stay_qt_free`` is what enforces that.

Two directories, and the distinction matters:

* ``docs/`` at the repository root holds the Markdown, and is **the source of
  truth**. It is what you edit, what ``git diff`` shows, and what gets
  published to the GitHub wiki by ``tools/publish_wiki.py``.
* ``gui/docs/`` holds HTML generated from it by ``tools/build_docs.py``, and
  is committed the way ``resources/PyXFocus.icns`` is committed -- a build
  artifact kept in the tree because the thing that consumes it (the running
  app, on Qt 5.9) cannot produce it.

Editing the Markdown without regenerating leaves those two out of step.
``build_docs.check()`` is the tripwire, and ``test_docs_html_is_current``
runs it, so the mismatch fails the suite rather than shipping.
"""

import collections
import hashlib
import os


PageSpec = collections.namedtuple('PageSpec', 'key title')

#: Every page in the documentation viewer, in reading order.
#:
#: NOT append-only -- and that is the difference from
#: :data:`PyXFocus.gui.tabs.TABS`, which is. No page index is persisted
#: anywhere: the viewer opens on ``PAGES[0]`` every time, nothing in
#: QSettings or a saved configuration refers to a page by position. So
#: reorder and insert freely; only the ``key`` is load-bearing.
#:
#: ``key`` must equal the Markdown basename. Link resolution
#: (:func:`key_for_href`) and the wiki publish both key off it, and the wiki
#: page name is derived from it too -- renaming a key renames a published
#: page and breaks anyone's bookmark.
PAGES = (
    PageSpec('Home', 'Home'),
    PageSpec('Installation', 'Installation'),
    PageSpec('Wolter-I-Explorer-GUI', 'Wolter-I Explorer (GUI)'),
    PageSpec('Scripting-and-Ray-Conventions', 'Scripting and Ray Conventions'),
    PageSpec('Architecture-and-Repository-Layout',
             'Architecture and Repository Layout'),
    PageSpec('Known-Limitations', 'Known Limitations'),
)

#: The wiki these pages are published to, and the Help menu's "view online".
WIKI_URL = 'https://github.com/jamccoy/PyXFocus_GUI/wiki'

_GUI_DIR = os.path.dirname(os.path.abspath(__file__))

#: Markdown, hand-written, canonical.
SOURCE_DIR = os.path.join(os.path.dirname(_GUI_DIR), 'docs')

#: HTML, generated by tools/build_docs.py, committed.
HTML_DIR = os.path.join(_GUI_DIR, 'docs')


def source_path(key):
    """The Markdown file for ``key``."""
    return os.path.join(SOURCE_DIR, key + '.md')


def html_path(key):
    """The generated HTML file for ``key``."""
    return os.path.join(HTML_DIR, key + '.html')


def keys():
    """Every page key, in reading order."""
    return [spec.key for spec in PAGES]


def title_for(key):
    """The display title for ``key``, or the key itself if it is not ours."""
    for spec in PAGES:
        if spec.key == key:
            return spec.title
    return key


def key_for_href(href):
    """
    The page key a link target refers to, or None if it is not one of ours.

    Accepts either extension -- ``Installation.md`` is what the Markdown
    sources link to (so the links also work when the folder is browsed on
    github.com) and ``Installation.html`` is what the generated pages link
    to. Anything else, including an http(s) URL, is not ours to resolve.
    """
    name = os.path.basename(href)
    for suffix in ('.md', '.html'):
        if name.endswith(suffix):
            name = name[:-len(suffix)]
            break
    else:
        return None
    return name if name in set(keys()) else None


def source_digest(key):
    """
    SHA-256 of the Markdown bytes for ``key``.

    Stamped into the generated HTML so ``build_docs.check()`` can tell
    "regenerated from this exact source" from "generated from something
    older", without needing a Markdown parser to find out.
    """
    with open(source_path(key), 'rb') as fh:
        return hashlib.sha256(fh.read()).hexdigest()
