#!/usr/bin/env python
"""Build a double-clickable macOS launcher for the Wolter-I Explorer.

    /opt/anaconda3/bin/python tools/make_launcher.py            # build it
    /opt/anaconda3/bin/python tools/make_launcher.py --check    # verify an existing one

Produces ``~/Documents/software_development/PyXFocus.app``: a minimal bundle
whose launch script has the interpreter and repository paths baked in at
build time.

The bundle is a build artifact and lives *outside* the repository (`*.app/`
is gitignored); this generator is the thing under version control, so the
launcher can always be rebuilt -- and must be, if the repo moves or the
interpreter changes.

**A .app that fails silently is useless**, so the launch script logs to
``~/Library/Logs/PyXFocus.log`` and raises a native dialog naming that log if
the GUI exits non-zero, rather than just bouncing the Dock icon once.

The interpreter is baked in as an absolute path, which is the whole point:
several Pythons on one machine is the normal case, and the compiled Fortran
extensions are built per interpreter, so "whichever python is on PATH" is
not a thing this application can be launched with.  Point it at the project's
own ``.venv/bin/python`` -- see requirements.txt -- and the bundle, the tests
and the extensions all refer to one environment.

(An earlier version of this note claimed the project had no virtualenv
"deliberately -- see the README". The README said no such thing; it said the
opposite, that becoming pip-installable was the proper fix. The absence was
an accident, and it cost a release where pyqtgraph was installed into a
Python the launcher never ran.)

There is still no console-script entry point, so the launcher must ``cd`` to
the *parent* of the ``PyXFocus`` folder before running
``python -m PyXFocus.gui.app``: the
package is imported by that name, and the folder has to be named that too,
so running from anywhere else reproduces the
``ModuleNotFoundError: No module named 'PyXFocus'`` trap the README warns
about elsewhere.
"""

from __future__ import print_function

import argparse
import os
import plistlib
import shutil
import stat
import subprocess
import sys

#: This file lives in <PyXFocus>/tools/. REPO_PARENT is where `python -m
#: PyXFocus.gui.app` must be run from -- the parent of the PyXFocus folder,
#: not the folder itself.
PYXFOCUS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO_PARENT = os.path.dirname(PYXFOCUS_DIR)

DEFAULT_APP = os.path.expanduser(
    '~/Documents/software_development/PyXFocus.app')
DEFAULT_PYTHON = '/opt/anaconda3/bin/python'
DISPLAY_NAME = 'Wolter-I Explorer'
BUNDLE_ID = 'com.pyxfocus.WolterExplorer'
EXECUTABLE_NAME = 'PyXFocus'

LAUNCH_SCRIPT = '''#!/bin/bash
# Generated by tools/make_launcher.py -- edit that, not this.
REPO_PARENT="{repo_parent}"
PY="{python}"
LOG="$HOME/Library/Logs/PyXFocus.log"
mkdir -p "$(dirname "$LOG")"

fail() {{
    /usr/bin/osascript -e "display alert \\"Wolter-I Explorer could not start\\" \\
        message \\"$1

Log: $LOG\\" as critical" >/dev/null 2>&1
    exit 1
}}

[ -x "$PY" ] || fail "No interpreter at $PY.
Rebuild the launcher with a working one:
    /opt/anaconda3/bin/python tools/make_launcher.py --python /path/to/python"

[ -d "$REPO_PARENT/PyXFocus" ] || fail "No PyXFocus folder at $REPO_PARENT.
Re-run tools/make_launcher.py, or the repository moved."

cd "$REPO_PARENT" || fail "Could not switch to $REPO_PARENT."
echo "--- $(date) ---" >> "$LOG"

"$PY" -m PyXFocus.gui.app >> "$LOG" 2>&1 || fail \\
    "The explorer exited with an error. This often means the Fortran
extensions were built for a different interpreter -- rebuild them with:
    $PY build_extensions.py"
'''


def _run(cmd):
    return subprocess.check_output(cmd, stderr=subprocess.STDOUT)


def _verify_interpreter(python_path):
    """Fail the build, not a later double-click, if $PY can't run the app."""
    if not os.path.isfile(python_path) or not os.access(python_path, os.X_OK):
        print('error: %s is not an executable file' % python_path,
              file=sys.stderr)
        return False
    probe = ('import sys; sys.path.insert(0, %r); '
            'import PyQt5.QtWidgets, PyXFocus.gui.app' % REPO_PARENT)
    try:
        _run([python_path, '-c', probe])
    except subprocess.CalledProcessError as err:
        print('error: %s cannot import the app:\n%s'
              % (python_path, err.output.decode('utf-8', 'replace')),
              file=sys.stderr)
        return False
    return True


def build(app_path, python_path):
    if os.path.isdir(app_path):
        shutil.rmtree(app_path)
    macos_dir = os.path.join(app_path, 'Contents', 'MacOS')
    resources_dir = os.path.join(app_path, 'Contents', 'Resources')
    os.makedirs(macos_dir)
    os.makedirs(resources_dir)

    launcher_path = os.path.join(macos_dir, EXECUTABLE_NAME)
    with open(launcher_path, 'w') as handle:
        handle.write(LAUNCH_SCRIPT.format(repo_parent=REPO_PARENT,
                                          python=python_path))
    mode = os.stat(launcher_path).st_mode
    os.chmod(launcher_path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    icns_src = os.path.join(PYXFOCUS_DIR, 'resources', 'PyXFocus.icns')
    has_icon = os.path.isfile(icns_src)
    if has_icon:
        shutil.copy(icns_src, os.path.join(resources_dir, 'PyXFocus.icns'))
    else:
        print('  no resources/PyXFocus.icns -- run tools/make_icon.py first '
              'for an icon')

    info = {
        'CFBundleName': DISPLAY_NAME,
        'CFBundleDisplayName': DISPLAY_NAME,
        'CFBundleIdentifier': BUNDLE_ID,
        'CFBundleVersion': '0.1.0',
        'CFBundleShortVersionString': '0.1.0',
        'CFBundleExecutable': EXECUTABLE_NAME,
        'CFBundlePackageType': 'APPL',
        'LSMinimumSystemVersion': '10.13',
        'NSHighResolutionCapable': True,
    }
    if has_icon:
        info['CFBundleIconFile'] = 'PyXFocus'
    with open(os.path.join(app_path, 'Contents', 'Info.plist'), 'wb') as handle:
        plistlib.dump(info, handle)

    print('built %s' % app_path)
    print('  interpreter: %s' % python_path)
    print('  runs from:   %s' % REPO_PARENT)
    print('  icon:        %s' % ('yes' if has_icon else 'no'))
    print('  double-click it in Finder; logs go to ~/Library/Logs/PyXFocus.log')


def check(app_path):
    """Verify the bundle's structure and that it still points somewhere real."""
    problems = []
    if not os.path.isdir(app_path):
        print('%s does not exist -- run without --check to build it' % app_path)
        return 1

    launcher_path = os.path.join(app_path, 'Contents', 'MacOS', EXECUTABLE_NAME)
    if not os.path.isfile(launcher_path):
        problems.append('launch script missing')
    elif not (os.stat(launcher_path).st_mode & stat.S_IXUSR):
        problems.append('launch script is not executable')
    else:
        text = open(launcher_path).read()
        try:
            repo_parent = text.split('REPO_PARENT="', 1)[1].split('"', 1)[0]
            python_path = text.split('PY="', 1)[1].split('"', 1)[0]
        except IndexError:
            problems.append('launch script does not look like ours -- rebuild it')
            repo_parent = python_path = None

        if repo_parent is not None:
            if not os.path.isdir(os.path.join(repo_parent, 'PyXFocus')):
                problems.append('points at %r, which has no PyXFocus folder'
                                % repo_parent)
            elif repo_parent != REPO_PARENT:
                problems.append('points at %r, but this repository is at %r'
                                % (repo_parent, REPO_PARENT))
            if python_path and not _verify_interpreter(python_path):
                problems.append('the baked-in interpreter %r can no longer '
                                'import the app' % python_path)
            # The bug this check exists to catch: a stale bundle whose
            # launcher predates a change to how the app is invoked.
            if 'PyXFocus.gui.app' not in text:
                problems.append('does not launch PyXFocus.gui.app -- rebuild it')

    plist_path = os.path.join(app_path, 'Contents', 'Info.plist')
    if not os.path.isfile(plist_path):
        problems.append('Info.plist missing')

    for problem in problems:
        print('  PROBLEM: %s' % problem)
    if not problems:
        print('%s: ok' % app_path)
    return 1 if problems else 0


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--app', default=DEFAULT_APP)
    parser.add_argument('--python', default=DEFAULT_PYTHON,
                        help='interpreter with PyQt5 and the built '
                             'extensions (default: %s)' % DEFAULT_PYTHON)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()

    if sys.platform != 'darwin':
        print('This builds a macOS .app bundle; on other platforms run '
              '`python -m PyXFocus.gui.app` directly.')
        return 1

    if args.check:
        return check(args.app)

    if not _verify_interpreter(args.python):
        print('\nRefusing to build a launcher pointing at an interpreter '
              'that cannot run the app.', file=sys.stderr)
        return 1

    build(args.app, args.python)
    return check(args.app)


if __name__ == '__main__':
    sys.exit(main())
